const { init, close, flush } = require('./cf-workers-sentry')

const {
    addGlobalEventProcessor,
    addBreadcrumb,
    captureException,
    captureEvent,
    captureMessage,
    configureScope,
    getHubFromCarrier,
    getCurrentHub,
    Hub,
    Scope,
    setContext,
    setExtra,
    setExtras,
    setTag,
    setTags,
    setUser,
    Span,
    withScope,
} = require('@sentry/core')

module.exports = {
    init, close, flush,
    addGlobalEventProcessor,
    addBreadcrumb,
    captureException,
    captureEvent,
    captureMessage,
    configureScope,
    getHubFromCarrier,
    getCurrentHub,
    Hub,
    Scope,
    setContext,
    setExtra,
    setExtras,
    setTag,
    setTags,
    setUser,
    Span,
    withScope,
}